---

- hosts: all
  gather_facts: False

  tasks:
    - name: Remove Redhat subscription
      redhat_subscription:
        state: absent
        username: "{{ rhn_username }}"
        password: "{{ rhn_password }}"
        pool_ids: "{{ rhn_pool_ids }}"

    - name: Decom OCP Environment
      ec2:
         state: 'absent'
         aws_access_key: "{{ aws_access_key }}"
         aws_secret_key: "{{ aws_secret_key }}"
         region: "{{ aws_region }}"
         instance_ids: "{{ ec2_id }}"
      delegate_to: "localhost"

    - name: Refresh EC2 cache
      command: './ec2.py --refresh-cache'
      args:
        chdir: 'inventory/'
      delegate_to: "localhost"
      run_once: true
    - name: Refresh in-memory EC2 cache
      meta: refresh_inventory
      delegate_to: "localhost"
      run_once: true
