---

###########################################################################
### OpenShift Master Vars
###########################################################################

openshift_master_api_port: 443  
openshift_master_console_port: 443

openshift_master_cluster_method: 'native'
openshift_master_cluster_hostname: 'lb.mitzicom.com'
openshift_master_cluster_public_hostname: 'loadbalancer.mitzicom.com' 
openshift_master_default_subdomain: 'apps.mitzicom.com' 

