---

###########################################################################
### OpenShift Metrics and Logging Vars
###########################################################################

# Enable cluster logging
openshift_logging_install_logging: 'True'  
openshift_logging_use_ops: 'True' 

openshift_logging_es_cluster_size: 3 
openshift_logging_es_number_of_replicas: 2 

openshift_logging_es_ops_cluster_size: 3 
openshift_logging_es_ops_number_of_replicas: 2 

# Run Elasticsearch, Kibana and the Curator on the Infra Nodes 
openshift_logging_es_nodeselector:  
  node-role.kubernetes.io/infra: true
openshift_logging_kibana_nodeselector:  
  node-role.kubernetes.io/infra: true
openshift_logging_curator_nodeselector:  
  node-role.kubernetes.io/infra: true

# Run Elasticsearch Ops, Kibana Ops and the Curator Ops on the Infra Nodes 
openshift_logging_es_ops_nodeselector:  
  node-role.kubernetes.io/infra: true
openshift_logging_kibana_ops_nodeselector:  
  node-role.kubernetes.io/infra: true
openshift_logging_curator_ops_nodeselector:  
  node-role.kubernetes.io/infra: true

openshift_logging_es_memory_limit: 1G
