---

- name: Create /usr/share/ansible dir
  file:
    dest: /usr/share/ansible
    state: directory
    owner: root
    group: root
    mode: 0755
  run_once: true
  delegate_to: localhost

- name: Clone the github openshift repo
  git:
    repo: 'https://github.com/openshift/openshift-ansible.git'
    dest: /usr/share/ansible/openshift-ansible
    version: openshift-ansible-3.11.24-1
  run_once: true
  delegate_to: localhost

